import type { ComponentType } from "react";
import type { ToolProps } from "./calculators";
import * as C from "./calculators";
import * as V from "./converters";
import * as T from "./text";
import * as G from "./generators";
import * as A from "./ai";
import * as P from "./productivity";

/** slug → component. Keep in sync with data/tools.ts. */
export const TOOL_COMPONENTS: Record<string, ComponentType<ToolProps>> = {
  porcentagem: C.Porcentagem,
  desconto: C.Desconto,
  "juros-simples": C.JurosSimples,
  "juros-compostos": C.JurosCompostos,
  "regra-de-tres": C.RegraDeTres,
  imc: C.IMC,
  "dividir-conta": C.DividirConta,
  "margem-de-lucro": C.MargemDeLucro,
  parcelamento: C.Parcelamento,
  "media-ponderada": C.MediaPonderada,
  roi: C.ROI,
  "calculadora-de-horas": C.CalculadoraDeHoras,
  "valor-hora-freelancer": C.ValorHoraFreelancer,
  "alcool-ou-gasolina": C.AlcoolOuGasolina,
  "calculadora-de-idade": C.CalculadoraDeIdade,
  "diferenca-entre-datas": C.DiferencaEntreDatas,
  "somar-dias": C.SomarDias,
  "contagem-regressiva": C.ContagemRegressiva,
  "dia-da-semana": C.DiaDaSemana,
  temperatura: V.Temperatura,
  comprimento: V.UnitConverter,
  peso: V.UnitConverter,
  velocidade: V.UnitConverter,
  area: V.UnitConverter,
  volume: V.UnitConverter,
  "dados-digitais": V.UnitConverter,
  tempo: V.UnitConverter,
  "base-numerica": V.BaseNumerica,
  cores: V.Cores,
  "timestamp-unix": V.TimestampUnix,
  base64: V.Base64,
  "url-encode": V.UrlEncode,
  "json-formatter": V.JsonFormatter,
  moeda: V.Moeda,
  "contador-de-palavras": T.ContadorDePalavras,
  "contador-de-caracteres": T.ContadorDeCaracteres,
  "maiusculas-minusculas": T.MaiusculasMinusculas,
  "limpar-texto": T.LimparTexto,
  "inverter-texto": T.InverterTexto,
  "gerador-de-slug": T.GeradorDeSlug,
  "lorem-ipsum": T.LoremIpsum,
  "extrair-emails-urls": T.ExtrairEmailsUrls,
  "ordenar-linhas": T.OrdenarLinhas,
  "frequencia-de-palavras": T.FrequenciaDePalavras,
  "resumidor-de-texto": T.ResumidorDeTexto,
  "tempo-de-leitura": T.TempoDeLeitura,
  "gerador-de-senha": G.GeradorDeSenha,
  "qr-code": G.QrCode,
  uuid: G.Uuid,
  "gerador-de-ideias": G.GeradorDeIdeias,
  "nomes-de-negocio": G.NomesDeNegocio,
  "paleta-de-cores": G.PaletaDeCores,
  "gerador-de-hashtags": G.GeradorDeHashtags,
  "gerador-de-titulos": G.GeradorDeTitulos,
  "gerador-de-bio": G.GeradorDeBio,
  "nome-de-usuario": G.NomeDeUsuario,
  "gerador-de-prompt-de-imagem": A.GeradorDePromptDeImagem,
  "melhorar-prompt": A.MelhorarPrompt,
  "estimador-de-tokens": A.EstimadorDeTokens,
  "custo-de-api-ia": A.CustoDeApiIa,
  "gerador-de-persona": A.GeradorDePersona,
  "roteiro-de-video": A.RoteiroDeVideo,
  "post-linkedin": A.PostLinkedin,
  "analisador-de-legibilidade": A.AnalisadorDeLegibilidade,
  "detector-de-tom": A.DetectorDeTom,
  pomodoro: P.Pomodoro,
  "lista-de-tarefas": P.ListaDeTarefas,
  "notas-rapidas": P.NotasRapidas,
  cronometro: P.Cronometro,
  "matriz-eisenhower": P.MatrizEisenhower,
  "roleta-de-decisao": P.RoletaDeDecisao,
  "gerador-de-okr": P.GeradorDeOkr,
};
